system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: Blog-Server
  dir: logs
jwt:
  expire: 240
  secret: xxx
  issuer: lingyuan
db:
- user: root
  password: root
  host: 192.168.179.135
  port: 3306
  db: blogx
  debug: false
  source: mysql
- user: root
  password: root
  host: 192.168.179.135
  port: 3307
  db: blogx
  debug: false
  source: mysql
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 2
site:
  siteInfo:
    title: CodeForge
    logo: ""
    beian: ""
    mode: 1
  project:
    title: LiXiaoYaoCareFree
    icon: /yyy.png
    webPath: uploads/index.html
  seo:
    keywords: LiXiaoYaoCareFree
    description: LiXiaoYaoCareFree1
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
    commentLine: 4
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 2210127151@qq.com
  authCode: zhflwiskxbyueafh
  sendNickname: LiXiaoYaoCareFree
  ssl: true
  tls: false
qq:
  appID: ""
  appKey: ""
  redirect: ""
qiNiu:
  enable: true
  accessKey: iAGmqdbwnY6ZZZPA_q79oHytI3kRv382F5KqukWB
  secretKey: HyNEbrunPiCovBR92wahb6pXAutk3zGifKNEi6-X
  bucket: codeforge
  uri: http://ssdeemm5d.hb-bkt.clouddn.com
  region: z1
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: njdfnhj6344t45347gsdhgsdh
  nickname: 小李
  avatar: /xxx/xxx
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images001
es:
  addr: 192.168.179.135:9200
  username: ""
  password: ""
  is_https: false
river:
  enable: true
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  source:
  - schema: blogx
    tables:
    - article_models
  rule:
  - schema: blogx
    table: article_models
    index: article_index
    type: _doc
    parent: ""
    id: []
    field:
      tag_list: tag_list,list