system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: Blog-Server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: lingyuan
db:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
db1:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 2
upload:
  size: 3
  whiteList:
    - jpg
    - jpeg
    - png
    - webp
    - gif
  uploadDir: images001
site:
  siteInfo:
    title: CodeForge1
    logo: ""
    beian: ""
    mode: 1
  project:
    title: CodeForge
    icon: /xxx.png
    webPath: uploads/index.html
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: false
    emailLogin: false
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: true
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 2210127151@qq.com
  authCode: zhflwiskxbyueafh
  sendNickname: LiXiaoYaoCareFree
  ssl: true
  tls: false
qq:
  appID: "2210127151"
  appKey: ""
  redirect: http://xxxxx
qiNiu:
  enable: true
  accessKey: iAGmqdbwnY6ZZZPA_q79oHytI3kRv382F5KqukWB
  secretKey: HyNEbrunPiCovBR92wahb6pXAutk3zGifKNEi6-X
  bucket: codeforge
  uri: http://ssdeemm5d.hb-bkt.clouddn.com
  region: z1
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: njdfnhj6344t45347gsdhgsdh
  nickname: 小李
  avatar: /xxx/xxx
