system:
  ip:
  port: 8080
  env: dev
  gin_mode: debug
log:
  app: Blog-Server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: lingyuan
db:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
db1:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
