system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: Blog-Server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: lingyuan
db:
- user: root
  password: root
  host: 192.168.179.135
  port: 3306
  db: blogx
  debug: false
  source: mysql
- user: root
  password: root
  host: 192.168.179.135
  port: 3307
  db: blogx
  debug: false
  source: mysql
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 2
site:
  siteInfo:
    title: CodeForge
    logo: ""
    beian: ""
    mode: 1
  project:
    title: LiXiaoYaoCareFree
    icon: /yyy.png
    webPath: uploads/index.html
  seo:
    keywords: LiXiaoYaoCareFree
    description: LiXiaoYaoCareFree1
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: true
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: false
    commentLine: 4
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 2210127151@qq.com
  authCode: zhflwiskxbyueafh
  sendNickname: LiXiaoYaoCareFree
  ssl: true
  tls: false
qq:
  appID: ""
  appKey: ""
  redirect: ""
qiNiu:
  enable: true
  accessKey: iAGmqdbwnY6ZZZPA_q79oHytI3kRv382F5KqukWB
  secretKey: HyNEbrunPiCovBR92wahb6pXAutk3zGifKNEi6-X
  bucket: codeforge
  uri: http://ssdeemm5d.hb-bkt.clouddn.com
  region: z1
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: njdfnhj6344t45347gsdhgsdh
  nickname: 小李
  avatar: /xxx/xxx
upload:
  size: 3
  whiteList:
  - jpg
  - jpeg
  - png
  - webp
  - gif
  uploadDir: images001
es:
  addr: 192.168.179.135:9200
  username: ""
  password: ""
  is_https: false
river:
  enable: true
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  source:
  - schema: blogx
    tables:
    - article_models
  rule:
  - schema: blogx
    table: article_models
    index: article_index
    type: _doc
    parent: ""
    id: []
    field:
      tag_list: tag_list,list
    tableinfo:
      schema: blogx
      name: article_models
      columns:
      - name: id
        type: 1
        collation: ""
        rawtype: bigint(20) unsigned
        isauto: true
        isunsigned: true
        enumvalues: []
        setvalues: []
      - name: created_at
        type: 6
        collation: ""
        rawtype: datetime(3)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: updated_at
        type: 6
        collation: ""
        rawtype: datetime(3)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: title
        type: 5
        collation: utf8mb4_general_ci
        rawtype: varchar(32)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: abstract
        type: 5
        collation: utf8mb4_general_ci
        rawtype: varchar(256)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: content
        type: 5
        collation: utf8mb4_general_ci
        rawtype: longtext
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: category_id
        type: 1
        collation: ""
        rawtype: bigint(20) unsigned
        isauto: false
        isunsigned: true
        enumvalues: []
        setvalues: []
      - name: tag_list
        type: 5
        collation: utf8mb4_general_ci
        rawtype: longtext
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: cover
        type: 5
        collation: utf8mb4_general_ci
        rawtype: varchar(256)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: user_id
        type: 1
        collation: ""
        rawtype: bigint(20) unsigned
        isauto: false
        isunsigned: true
        enumvalues: []
        setvalues: []
      - name: look_count
        type: 1
        collation: ""
        rawtype: bigint(20)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: digg_count
        type: 1
        collation: ""
        rawtype: bigint(20)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: comment_count
        type: 1
        collation: ""
        rawtype: bigint(20)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: collect_count
        type: 1
        collation: ""
        rawtype: bigint(20)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: open_comment
        type: 1
        collation: ""
        rawtype: tinyint(1)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      - name: status
        type: 1
        collation: ""
        rawtype: tinyint(4)
        isauto: false
        isunsigned: false
        enumvalues: []
        setvalues: []
      indexes:
      - name: PRIMARY
        columns:
        - id
        cardinality:
        - 5
      pkcolumns:
      - 0
      unsignedcolumns:
      - 0
      - 6
      - 9
    filter: []
    pipeline: ""
  bulk_size: 128
