system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: Blog-Server
  dir: logs
jwt:
  expire: 3
  secret: xxx
  issuer: lingyuan
db:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
db1:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  db: blogx
  debug: false
  source: mysql
redis:
  addr: 127.0.0.1:6379
  password: "1234"
  db: 2
site:
  siteInfo:
    title: CodeForge
    logo: ""
    beian: ""
    mode: 1
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: ""
    qq: ""
    wechat: ""
    gitee: ""
    bilibili: ""
    github: ""
  login:
    qqLogin: false
    usernamePwdLogin: false
    emailLogin: false
    captcha: false
  indexRight:
    list: []
  article:
    noExamine: true
email:
  domain: ""
  port: 0
  sendEmail: ""
  authCode: ""
  sendNickname: ""
  ssl: false
  tls: false
qq:
  appID: "2210127151"
  appKey: ""
  redirect: http://xxxxx
qiNiu:
  enable: false
  accessKey: ""
  secretKey: ""
  bucket: ""
  uri: ""
  region: ""
  prefix: ""
  size: 0
ai:
  enable: false
  secretKey: njdfnhj6344t45347gsdhgsdh
  nickname: 小李
  avatar: /xxx/xxx
