system:
  ip: ""
  port: 8080
  gin_mode: debug
  env: dev
log:
  app: blogx_server
  dir: logs
db:
  - user: root
    password: root
    host: 10.2.0.2
    port: 3306
    db: blogx
    debug: false
    source: mysql
redis:
  addr: 10.2.0.6:6379
  password: ""
  db: 2
es:
  addr: 10.2.0.5:9200
  username: ""
  password: ""
  is_https: false
  enable: true
river:
  enable: true
  server_id: 1001
  flavor: mysql
  data_dir: ./var
  source:
    - schema: blogx
      tables:
        - article_models
        - text_models
  rule:
    - schema: blogx
      table: article_models
      index: article_index
      type: _doc
      field:
        tag_list: tag_list,list
    - schema: blogx
      table: text_models
      index: text_index
      type: _doc
  bulk_size: 128
jwt:
  expire: 240
  secret: xxx
  issuer: lingyuan
site:
  siteInfo:
    title: ""
    enTitle: ""
    slogan: ""
    logo: ""
    beian: ""
    mode: 1
  project:
    title: ""
    icon: ""
    webPath: ""
  seo:
    keywords: ""
    description: ""
  about:
    siteDate: "2025-03-13"
    qq:
    wechat:
    gitee:
    bilibili: https://space.bilibili.com/1670692465
    github: https://github.com/LiXiaoYaoCareFree
  login:
    qqLogin: false
    usernamePwdLogin: true
    emailLogin: false
    captcha: false
  indexRight:
    list:
      - title: 独家推广
        enable: true
      - title: 用户反馈
        enable: false
      - title: 标签云
        enable: true
      - title: 文章推荐
        enable: true
      - title: 关于我们
        enable: true
      - title: 作者推荐
        enable: true
  article:
    noExamine: true
    commentLine: 4
email:
  domain: smtp.qq.com
  port: 587
  sendEmail: 2210127151@qq.com
  authCode: zhflwiskxbyueafh
  sendNickname: LiXiaoYaoCareFree
  ssl: true
  tls: false
qq:
  appID: ""
  appKey: ""
  redirect: ""
qiNiu:
  enable: true
  accessKey: iAGmqdbwnY6ZZZPA_q79oHytI3kRv382F5KqukWB
  secretKey: HyNEbrunPiCovBR92wahb6pXAutk3zGifKNEi6-X
  bucket: codeforge
  uri: http://ssdeemm5d.hb-bkt.clouddn.com
  region: z1
  prefix: blogx
  size: 3
  expiry: 60
ai:
  enable: false
  secretKey: sk-zfauDNTFOZlmyOIXAZgvhpZj82GPom6JKbhTlzNZRIMlWB1S
  nickname: 小枫
  avatar: /xxx/xxx
  abstract: Hello，我是你的AI小管家,你可以叫我逍遥云,我可以根据你的描述在全站文章中去找到你所喜欢的文章,赶紧来试试吧！
upload:
  size: 3
  whiteList:
    - jpg
    - jpeg
    - png
    - webp
    - gif
  uploadDir: images001

